import { Activity, Category, DayId, Timeslot } from './types';

export const days: Array<{ id: DayId; label: string; short: string; accent: string }> = [
  { id: '2026-07-09', label: 'Donnerstag, 09.07.', short: 'Do 09.07.', accent: '#ef7d57' },
  { id: '2026-07-10', label: 'Freitag, 10.07.', short: 'Fr 10.07.', accent: '#34a0a4' },
  { id: '2026-07-11', label: 'Samstag, 11.07.', short: 'Sa 11.07.', accent: '#6c8ae4' },
  { id: '2026-07-12', label: 'Sonntag, 12.07.', short: 'So 12.07.', accent: '#d676b8' },
  { id: '2026-07-13', label: 'Montag, 13.07.', short: 'Mo 13.07.', accent: '#8a9a5b' },
];

export const timeslots: Timeslot[] = ['Vormittag', 'Nachmittag', 'Abend'];

export const categories: Category[] = [
  'Reise',
  'Kultur',
  'Bier & Bars',
  'Essen',
  'Special Activity',
  'Aussicht',
  'Nachtleben',
  'Backup bei Regen',
];

export const categoryMeta: Record<Category, { color: string; icon: string }> = {
  Reise: { color: '#5f6f8f', icon: '✈' },
  Kultur: { color: '#8b5e3c', icon: '◆' },
  'Bier & Bars': { color: '#c98716', icon: '●' },
  Essen: { color: '#d85648', icon: '◒' },
  'Special Activity': { color: '#7b61ff', icon: '✦' },
  Aussicht: { color: '#258f84', icon: '◐' },
  Nachtleben: { color: '#5264d8', icon: '✧' },
  'Backup bei Regen': { color: '#4a7b9d', icon: '☂' },
};

export const defaultParticipants = ['Andi', 'Steffen', 'Niko', 'Markus', 'Stefan', 'Philipp'];

const all = defaultParticipants;

export const seedActivities: Activity[] = [
  {
    id: 'arrival',
    title: 'Ankunft in Bratislava',
    dayId: '2026-07-09',
    timeslot: 'Abend',
    timeRange: 'ab 18:00',
    category: 'Reise',
    description: 'Ankommen, Unterkunft beziehen, erster Spaziergang durch die Altstadt.',
    location: 'Bratislava Old Town',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Bratislava+Old+Town',
    costPerPerson: 0,
    reservationStatus: 'Offen',
    notes: 'Check-in-Zeit und Gepäckoptionen ergänzen.',
    attendees: all,
    likedBy: [],
    priority: 'Must-have',
    booked: false,
    favorite: true,
  },
  {
    id: 'first-beer',
    title: 'Erstes Bier in der Altstadt',
    dayId: '2026-07-09',
    timeslot: 'Abend',
    timeRange: '21:30',
    category: 'Bier & Bars',
    description: 'Entspannter Start mit slowakischem Bier.',
    location: 'Bratislavský Meštiansky Pivovar',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Bratislavsky+Mestiansky+Pivovar+Bratislava',
    costPerPerson: 12,
    reservationStatus: 'Offen',
    notes: '',
    attendees: all,
    likedBy: [],
    priority: 'Optional',
    booked: false,
    favorite: false,
  },
  {
    id: 'castle',
    title: 'Bratislava Burg',
    dayId: '2026-07-10',
    timeslot: 'Vormittag',
    timeRange: '10:00-12:00',
    category: 'Kultur',
    description: 'Kultur, Aussicht und kurzer Stadtrundgang.',
    location: 'Bratislava Castle',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Bratislava+Castle',
    costPerPerson: 8,
    reservationStatus: 'Offen',
    notes: 'Gute Fotostelle einplanen.',
    attendees: all,
    likedBy: [],
    priority: 'Must-have',
    booked: false,
    favorite: true,
  },
  {
    id: 'old-town',
    title: 'Altstadt, Michaelertor und St.-Martins-Dom',
    dayId: '2026-07-10',
    timeslot: 'Nachmittag',
    timeRange: '12:30-14:30',
    category: 'Kultur',
    description: 'Kompakte Altstadt-Runde mit den wichtigsten Spots.',
    location: 'Michael’s Gate Bratislava',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Michael%27s+Gate+Bratislava',
    costPerPerson: 0,
    reservationStatus: 'Offen',
    notes: '',
    attendees: all,
    likedBy: [],
    priority: 'Must-have',
    booked: false,
    favorite: false,
  },
  {
    id: 'ufo',
    title: 'UFO Tower / UFO Skywalk',
    dayId: '2026-07-10',
    timeslot: 'Abend',
    timeRange: '18:30',
    category: 'Special Activity',
    description: 'Aussicht über Bratislava und optional Skywalk außen am UFO Tower.',
    location: 'UFO Observation Deck',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=UFO+Observation+Deck+Bratislava',
    costPerPerson: 15,
    reservationStatus: 'Angefragt',
    notes: 'Skywalk vorab prüfen.',
    attendees: all,
    likedBy: [],
    priority: 'Optional',
    booked: false,
    favorite: false,
  },
  {
    id: 'bunker',
    title: 'Bunker-Tour',
    dayId: '2026-07-11',
    timeslot: 'Vormittag',
    timeRange: '10:30-12:30',
    category: 'Special Activity',
    description: 'Historische Bunkeranlage an der ehemaligen Grenze. Keine Waffen-Aktivität, sondern Geschichte und Kalter Krieg.',
    location: 'Bunker B-S 8 Cemetery',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Bunker+B-S+8+Cemetery+Bratislava',
    costPerPerson: 12,
    reservationStatus: 'Offen',
    notes: '',
    attendees: all,
    likedBy: [],
    priority: 'Optional',
    booked: false,
    favorite: false,
  },
  {
    id: 'devin',
    title: 'Devín Burg',
    dayId: '2026-07-11',
    timeslot: 'Nachmittag',
    timeRange: '15:00-18:00',
    category: 'Aussicht',
    description: 'Historische Burg am Zusammenfluss von Donau und March.',
    location: 'Devín Castle',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Devin+Castle+Bratislava',
    costPerPerson: 10,
    reservationStatus: 'Offen',
    notes: 'Anfahrt per Bus oder Bolt vergleichen.',
    attendees: all,
    likedBy: [],
    priority: 'Must-have',
    booked: false,
    favorite: true,
  },
  {
    id: 'craft-beer',
    title: 'Craft Beer Abend',
    dayId: '2026-07-11',
    timeslot: 'Abend',
    timeRange: '20:00',
    category: 'Bier & Bars',
    description: 'Kleine selbst organisierte Craft-Beer-Tour.',
    location: 'Bratislava city center craft beer',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Craft+Beer+Bratislava',
    costPerPerson: 25,
    reservationStatus: 'Offen',
    notes: '2-3 Bars auswählen, nicht zu viel laufen.',
    attendees: all,
    likedBy: [],
    priority: 'Must-have',
    booked: false,
    favorite: true,
  },
  {
    id: 'beer-bike',
    title: 'Beer Bike',
    dayId: '2026-07-12',
    timeslot: 'Nachmittag',
    timeRange: '16:00',
    category: 'Special Activity',
    description: 'Gemeinsame Beer-Bike-Tour durch Bratislava.',
    location: 'Bratislava Beer Bike',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Bratislava+Beer+Bike',
    costPerPerson: 35,
    reservationStatus: 'Angefragt',
    notes: 'Anbieter und Mindestanzahl klären.',
    attendees: all,
    likedBy: [],
    priority: 'Optional',
    booked: false,
    favorite: false,
  },
  {
    id: 'final-night',
    title: 'Abschlussabend',
    dayId: '2026-07-12',
    timeslot: 'Abend',
    timeRange: '19:30-offen',
    category: 'Nachtleben',
    description: 'Gutes Essen, Bars und letzter gemeinsamer Abend.',
    location: 'Bratislava Old Town',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Bars+Bratislava+Old+Town',
    costPerPerson: 45,
    reservationStatus: 'Offen',
    notes: 'Restaurant fürs Dinner vormerken.',
    attendees: all,
    likedBy: [],
    priority: 'Must-have',
    booked: false,
    favorite: true,
  },
];
